// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf0CIOGB8mdgkl0CfWjsXMBr6ARrLmoNg',
    appId: '1:907550787976:web:d9390820f467af7846123d',
    messagingSenderId: '907550787976',
    projectId: 'raincheck-ca78a',
    authDomain: 'raincheck-ca78a.firebaseapp.com',
    storageBucket: 'raincheck-ca78a.appspot.com',
    measurementId: 'G-VSF08JY6H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-lwEBAW_B-Tl3xBWCC8n8v10iIOU_TM',
    appId: '1:907550787976:android:d342afe866e8f0f146123d',
    messagingSenderId: '907550787976',
    projectId: 'raincheck-ca78a',
    storageBucket: 'raincheck-ca78a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2S_a7lM-bCFBBpSxUxfTcUh3GlIAh5Y',
    appId: '1:907550787976:ios:e711a3c62e7a4e4e46123d',
    messagingSenderId: '907550787976',
    projectId: 'raincheck-ca78a',
    storageBucket: 'raincheck-ca78a.appspot.com',
    iosClientId: '907550787976-f0oo7b29bjeqhrsqldi787hnndgebmu4.apps.googleusercontent.com',
    iosBundleId: 'com.kazoom.raincheck',
  );
}
